### ISSUE TITLE
Do those papers exist with codes?

### ISSUE THREAD

**Issue by z16973** [ykotseruba/attention_and_driving#1]
Hi,ykotseruba,
      Do those papers exist with codes?Just like this:https://github.com/aras62/vision-based-prediction/blob/master/papers/papers_with_code.md#top

**Comment by ykotseruba** [comment]
Hi, some of the papers have code, many don't. If you look at self-driving or scene gaze category, there are many links to implementations there. I'll try to make a separate list to make finding them easier.
