### ISSUE TITLE
Paper in a wrong topic

### ISSUE THREAD

**Issue by MustafaLotfi** [ykotseruba/attention_and_driving#4]
First of all I appreciate your well job of gathering these correlated papers.

Then I wanted to mention that in the drowsiness_detection topic there is a paper named "Real-time Detection of Distracted Driving using Dual Cameras". As it's clear this paper should move to the distraction_detection topic.

**Comment by ykotseruba** [comment]
Hi @MustafaLotfi, thanks for your comment. The authors of the paper you mention include "drowsy" as one of the distracted behaviors, so the paper is included in both lists.

**Comment by MustafaLotfi** [comment]
Then you are right.
Thanks 👌
